{% set name = "doct" %}
{% set version = "1.0.6" %}
{% set sha256 = "743adc5944aa9073c7028a50c8493ad7c83faf90e93eabc862b5ffdb53227918" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - humanize
    - prettytable
    - six

test:
  imports:
    - doct

about:
  home: https://github.com/NSLS-II/doct
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A read-only dottable dictionary
