{% set name = "doct" %}
{% set version = "1.1.0" %}
{% set sha256 = "966930179cce0788d922d877c65385bd851df5dc2f0a1009579607e3eed6bd5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - humanize
    - prettytable

test:
  imports:
    - doct

about:
  home: https://github.com/NSLS-II/doct
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A read-only dottable dictionary
